// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1Lable1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1Lable1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1Lable1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1Lable1, -1);
    lv_obj_set_y(ui_Screen1Lable1, -30);
    lv_obj_set_align(ui_Screen1Lable1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1Lable1, "text");

    ui_Screen1Lable2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1Lable2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1Lable2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1Lable2, -1);
    lv_obj_set_y(ui_Screen1Lable2, 16);
    lv_obj_set_align(ui_Screen1Lable2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1Lable2, "text");

}
